image:
  #repository: mariadb
  tag: 10.11

auth:
  database: "fleet_db"
  username: "fleet"
  existingSecret: "mariadb-secrets"
  
primary:
  persistence:
    enabled: true
    existingClaim: "mariadb-pvc"
  pdb:
    create: false

secondary:
  replicaCount: 0

volumePermissions:
  enabled: true

networkPolicy:
  enabled: false

initdbScripts:
  init_db.sql: |
    CREATE DATABASE fleet_db;